entity_print.settings:
  type: config_object
  label: 'Entity Print settings.'
  mapping:
    default_css:
      type: boolean
      label: 'Enable the default CSS.'
    force_download:
      type: boolean
      label: 'Force download of PDF'
    binary_location:
      type: string
      label: 'Location of the PDF engine binary.'
    pdf_engine:
      type: string
      label: 'The plugin id of the PDF engine to use.'
