printable_entities:
  - node
  - comment
  - user
open_target_blank: true
css_include: ''
extract_links: ''
save_pdf: true
pdf_tool: null
paper_size: Letter
page_orientation: portrait
path_to_binary: ''
pdf_location: ''
send_to_printer: true
close_window: true
list_attribute: true
printable_print_link_locations:
  - node
printable_pdf_link_locations:
  - ''
